language: node_js
node_js:
  - 17
install:
  - npm install
script:
  - npm test
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: multiplayer-pictionary
  on: master